### ISSUE TITLE
Editing Print Format vs Result - Gives different output

### ISSUE THREAD

**Issue by ghost** [frappe/print_designer#17]
This is how it looks like for A4 in Report Builder
![image](https://github.com/frappe/print_designer/assets/26267551/188e8865-d7d1-43b6-abbb-e2ec423962d0)

However, it looks completely different in the final output. The formatting is completed off.
![image](https://github.com/frappe/print_designer/assets/26267551/3b2d9fe4-2f35-4f58-bbb0-e7625f3a4628)

Also, footer and header whatever we setting in the report builder is not displaying in the print format

**Comment by maharshivpatel** [comment]
Please try on a new site.
Framework should be on develop branch.

Frappe / Print Designer requires at least  [version 0.12.5 with patched qt](https://frappeframework.com/docs/v14/user/en/installation#pre-requisites)

Install correct version by following [installation guide](https://frappeframework.com/docs/v14/user/en/installation) and confirm : 

```
wkhtmltopdf --version
```
output should be similar to `wkhtmltopdf 0.12.6 (with patched qt)`

**Comment by maharshivpatel** [comment]
Closing as user account that created this issue has been deleted

**Comment by alpeshchauhan01** [comment]
@[alpeshchauhan01](https://github.com/alpeshchauhan01)
alpeshchauhan01 commented [Oct 18, 2023](https://github.com/frappe/print_designer/issues/17#issuecomment-1768063213)

First of many many thanks to Mr. Maharshibhai Patel for developing very useful app in erpnext. My work is become too easy due to this module.

I also face this type of issue listed above. PDF output is not same as we are set in template page. but after readying of this thread I see my mistake .....

My mistake is " I install only wkhtmltopdf 0.12.6 instead of wkhtmltopdf 0.12.6 (with patched qt)

Because of by default installation from github is not (with patched qt)

So i Uninstall wkhtmltopdf 0.12.6 fom terminal
Then,

Then i Download wkhtmltopdf 0.12.6 (with patched qt) from its website link given below..........
(For Ubuntu 22.04 & arm 64, But You can download as per your architecture of your system)

Link ---> https://wkhtmltopdf.org/downloads.html
and Install it,

Done!
My Problem is solved.

Many many Thanks to Respected & Helpful person
Mr. Maharshibhai Patel

**Comment by alpeshchauhan01** [comment]
alpeshchauhan01 commented https://github.com/frappe/print_designer/issues/17#issuecomment-1768063213

First of many many thanks to Mr. Maharshibhai Patel for developing very useful app in erpnext. My work is become too easy due to this module.

I also face this type of issue listed above. PDF output is not same as we are set in template page. but after readying of this thread I see my mistake .....

My mistake is " I install only wkhtmltopdf 0.12.6 instead of wkhtmltopdf 0.12.6 (with patched qt)

Because of by default installation from github is not (with patched qt)

So i Uninstall wkhtmltopdf 0.12.6 fom terminal
Then,

Then i Download wkhtmltopdf 0.12.6 (with patched qt) from its website link given below..........
(For Ubuntu 22.04 & amd 64, But You can download as per your architecture of your system)

Link ---> https://wkhtmltopdf.org/downloads.html
and Install it,

Done!
My Problem is solved.

Many many Thanks to Respected & Helpful person
Mr. Maharshibhai Patel
