### ISSUE TITLE
Rectangle not showing in preview

### ISSUE THREAD

**Issue by nilpatel42** [frappe/print_designer#293]
Rectangle not showing in preview, Some Time Child Table Set over the Rectangle in Preview,

![image](https://github.com/frappe/print_designer/assets/135511086/524f48f7-59fe-47fb-aba6-c3bbe65d7ec0)

![image](https://github.com/frappe/print_designer/assets/135511086/091df4db-13ae-4c60-9b21-691671e82b58)

Also i Checked  
```
wkhtmltopdf --version
wkhtmltopdf 0.12.6.1 (with patched qt)
```

ERPNext: v15.27.7 (version-15)
Frappe Framework: v15.30.0 (version-15)
Print Designer: v1.2.0 (develop)

**Comment by yamenzk** [comment]
I had the same issue as well, it only happens when you have multiple pages. I assume the issue behind this is that the designer tries to add content from the following page whenever there is blank area on the prior page. 
A workaround that has worked for me is to add an empty rectangle at the end of every page which will act as a page break. 

Note: the height of the rectangle might bug your page dimensions (happened to me on custom dimensions with no header and footer), experiment with its height until you reach a good spot.

**Comment by nilpatel42** [comment]
@yamenzk Thank for reply

I tried but not working, can you share SS of your print format ?

**Comment by maharshivpatel** [comment]
@nilpatel42 rectangle is there it's the border that is removed. fixing this..... you can confirm this by setting color in rectangle's background
