### ISSUE TITLE
Print design is not showing exactly the same output 

### ISSUE THREAD

**Issue by yhennie** [frappe/print_designer#69]
the size in the design and location  is different from the frappe 
 This is what it looks in frappe design 
![image](https://github.com/frappe/print_designer/assets/61680603/203423cd-2a41-4e0c-ab03-8162c0466a9f)

and this what looks on frappe 
![image](https://github.com/frappe/print_designer/assets/61680603/3cc805c3-c363-4f59-9c54-917c9f7e9f45)

the location of the lines and text is not proportion and not accurate display

**Comment by maharshivpatel** [comment]
### can you share your format like this :
You can paste the data here ( change any personal info )

https://github.com/frappe/print_designer/assets/39730881/b7b761c7-a2b1-43d4-a3b3-0dde25ba9699

**Comment by alpeshchauhan01** [comment]
First of many many thanks to Mr. Maharshibhai Patel for developing very useful app in erpnext. My work is become too easy due to this module.

**I also face this type of issue listed above. But now its solved**

PDF output is not same as we are set in template page. but after reading of issue No. 17 thread I see my mistake .....

My mistake is " I install only wkhtmltopdf 0.12.6 instead of wkhtmltopdf 0.12.6 (with patched qt)

Because of by default installation from github is not (with patched qt)

So i Uninstall wkhtmltopdf 0.12.6 fom terminal
Then,

Then i Download wkhtmltopdf 0.12.6 (with patched qt) from its website link given below..........

(For Ubuntu 22.04 & amd 64, But You can download as per your architecture of your system and Find it **.deb** file in Downloads folder & Install it **.deb** file by Right Click "Software Install" Application. See Screenshot 1 & 2)

Link ---> https://wkhtmltopdf.org/downloads.html
and Install it,

Done!
My Problem is solved.

Many many Thanks to Respected & Helpful person
Mr. Maharshibhai Patel


![1](https://github.com/frappe/print_designer/assets/55324054/78ba4169-3442-48f7-96a1-46e26299b617)
![2](https://github.com/frappe/print_designer/assets/55324054/8d2034bb-2505-42ff-b167-f21b05b0699a)

**Comment by maharshivpatel** [comment]
@yhennie is you issue resolved ? please share more information if you are still facing it. 

@alpeshchauhan01 's solution can be effective if you have incorrect wkhtmltopdf version installed.

**Comment by yhennie** [comment]
> @yhennie is your issue resolved ? please share more information if you are still facing it.

I managed to do it  on print format I manual adjusted the codes here so the design is fit on the page but using the actual print designer its not working. 

![image](https://github.com/frappe/print_designer/assets/61680603/bd34a382-cbd1-45f4-89ca-3823fc5d6685)

**Comment by maharshivpatel** [comment]
@yhennie please share your format so i can fix that

**Comment by maharshivpatel** [comment]
@yhennie as you haven't provided format, i am unable to replicate this and as you have solved it for you on your own. I am closing this issue for now. If you face the issue in future please. Reopen or create new Issue.
